export enum Character {
	BART_CASSIDY = `Bart Cassidy`,
	BLACK_JACK = `Black Jack`,
	CALAMITY_JANET = `Calamity Janet`,
	EL_GRINGO = `El Gringo`,
	JESSE_JONES = `Jesse Jones`,
	JOURDONNAIS = `Jourdonnais`,
	KIT_CARLSON = `Kit Carlson`,
	LUCKY_DUKE = `Lucky Duke`,
	PAUL_REGRET = `Paul Regret`,
	PEDRO_RAMIREZ = `Pedro Ramirez`,
	ROSE_DOOLAN = `Rose Doolan`,
	SID_KETCHUM = `Sid Ketchum`,
	SLAB_THE_KILLER = `Slab the Killer`,
	SUZY_LAFAYETTE = `Suzy Lafayette`,
	VULTURE_SAM = `Vulture Sam`,
	WILLY_THE_KID = `Willy the Kid`,

	// Dodge City
	APACHE_KID = `Apache Kid`,
	BELLE_STAR = `Belle Star`,
	BILL_NOFACE = `Bill Noface`,
	CHUCK_WENGAM = `Chuck Wengam`,
	DOC_HOLYDAY = `Doc Holyday`,
	ELENA_FUENTE = `Elena Fuente`,
	GREG_DIGGER = `Greg Digger`,
	HERB_HUNTER = `Herb Hunter`,
	JOSE_DELGADO = `José Delgado`,
	MOLLY_STARK = `Molly Stark`,
	PAT_BRENNAN = `Pat Brennan`,
	PIXIE_PETE = `Pixie Pete`,
	SEAN_MALLORY = `Sean Mallory`,
	TEQUILA_JOE = `Tequila Joe`,
	VERA_CUSTER = `Vera Custer`,
}
