import { repeat } from '../fun/repeat'
import { Card } from './Card'

export const DECK: readonly Card[] = [
	...repeat(Card.BANG, 30),
	...repeat(Card.BARREL, 2),
	...repeat(Card.BEER, 10),
	...repeat(Card.BIBLE, 2),
	...repeat(Card.BRAWL, 2),
	...repeat(Card.CANTEEN, 2),
	...repeat(Card.CAN_CAN, 2),
	...repeat(Card.CAT_BALOU, 4),
	...repeat(Card.DERRINGER, 2),
	...repeat(Card.DODGE, 4),
	...repeat(Card.DUEL, 4),
	...repeat(Card.DYNAMITE, 2),
	...repeat(Card.GATLING, 2),
	...repeat(Card.GENERAL_STORE, 2),
	...repeat(Card.HIDEOUT, 2),
	...repeat(Card.INDIANS, 4),
	...repeat(Card.IRON_PLATE, 2),
	...repeat(Card.JAIL, 2),
	...repeat(Card.KNIFE, 2),
	...repeat(Card.MISSED, 20),
	...repeat(Card.MUSTANG, 2),
	...repeat(Card.PANIC, 4),
	...repeat(Card.PONY_EXPRESS, 2),
	...repeat(Card.PUNCH, 2),
	...repeat(Card.RAG_TIME, 2),
	...repeat(Card.REMINGTON_3, 2),
	...repeat(Card.REV_CARABINE_4, 2),
	...repeat(Card.SALOON, 2),
	...repeat(Card.SCHOFIELD_2, 2),
	...repeat(Card.SCOPE, 2),
	...repeat(Card.SOMBRERO, 2),
	...repeat(Card.STAGECOACH, 2),
	...repeat(Card.TEN_GALLON_HAT, 2),
	...repeat(Card.TEQUILA, 2),
	...repeat(Card.VOLCANIC_1, 2),
	...repeat(Card.WELLS_FARGO, 2),
	...repeat(Card.WHISKY, 2),
	...repeat(Card.WINCHESTER_5, 2),
]
